services:
  letter-compile:
    image: yyupw/letter-pdf:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      cache_from:
        - yyupw/letter-pdf:latest
    volumes:
      - .:/workdir
    working_dir: /workdir
    command: /bin/bash -c make
